import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";

const base = process.env.FORGE_BROWSER_URL || "http://127.0.0.1:55174";
const api = process.env.FORGE_BROWSER_API_URL || "http://127.0.0.1:55001";
if (![base, api].every(value => new URL(value).hostname === "127.0.0.1")) throw new Error("Local disposable servers only");
test("prompt, native responsive preview, explicit apply, manual save and scoped AI edit", async ({ browser }) => {
  test.setTimeout(120000);
  const fixture = JSON.parse(readFileSync(process.env.FORGE_BROWSER_FIXTURE_PATH!, "utf8"));
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  await context.addCookies([{ name: "forge_session", value: fixture.token, domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
  await context.route("**/*", route => new URL(route.request().url()).hostname === "127.0.0.1" ? route.continue() : route.abort());
  const page = await context.newPage();
  const readWebsite = async () => (await (await context.request.get(`${api}/api/websites/${fixture.websiteId}`)).json()).website;
  await page.goto(`${base}/editor/${fixture.websiteId}`);
  await page.getByRole("button", { name: "Design with AI", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Stitch and Claude website designer" });
  await dialog.getByRole("button", { name: "Use sample brief" }).click();
  const queuedResponse = page.waitForResponse(response => response.url().endsWith(`/ai/websites/${fixture.websiteId}/executions`) && response.request().method() === "POST");
  await dialog.getByRole("button", { name: "Generate proposal", exact: true }).click();
  const queued = await (await queuedResponse).json();
  await expect(dialog.getByRole("button", { name: "Apply changes", exact: true })).toBeVisible({ timeout: 40000 });
  const before = await readWebsite();
  const execution = (await (await context.request.get(`${api}/api/v1/ai/executions/${queued.executionId}`)).json()).execution;
  expect(before.documentVersion).toBe(execution.expectedDocumentVersion);
  const heading = dialog.getByRole("heading", { name: "Editorial academy", exact: true });
  await expect(heading).toHaveCSS("font-size", "48px");
  await dialog.getByLabel("Preview viewport").selectOption("mobile");
  await expect(heading).toHaveCSS("font-size", "28px");
  await dialog.getByRole("button", { name: "Apply changes", exact: true }).click();
  await expect(dialog).toHaveCount(0, { timeout: 20000 });
  const editable = page.locator('[contenteditable="true"]').filter({ hasText: "Editorial academy" }).first();
  await expect(editable).toBeVisible();
  await editable.fill("Manually improved heading"); await page.keyboard.press("Tab");
  await page.getByRole("button", { name: "Design with AI", exact: true }).click();
  await dialog.getByLabel("AI operation").selectOption("EDIT_DOCUMENT");
  await dialog.getByLabel("Design brief").fill("Rewrite the first heading to make it more direct.");
  await dialog.getByRole("button", { name: "Generate proposal", exact: true }).click();
  await expect(dialog.getByRole("heading", { name: "AI edited heading", exact: true })).toBeVisible({ timeout: 40000 });
  expect(JSON.stringify((await readWebsite()).editorData)).toContain("Manually improved heading");
  await dialog.getByRole("button", { name: "Discard proposal", exact: true }).click();
  await dialog.getByRole("button", { name: "Back to editing", exact: true }).click();
  await page.reload();
  await expect(page.locator('[contenteditable="true"]').filter({ hasText: "Manually improved heading" }).first()).toBeVisible();
  await context.close();
});
