import fs from "fs";
import path from "path";

const registry = [
  // Module 25: WordPress Core & Publishing (25 features)
  { id: "F-484", module: 25, name: "WordPress Connector Plugin", priority: "mandatory", testLevel: ["UI", "API", "WORDPRESS_E2E"] },
  { id: "F-485", module: 25, name: "Site Connection", priority: "mandatory", testLevel: ["UI", "API", "PERSISTENCE", "WORDPRESS_E2E"] },
  { id: "F-486", module: 25, name: "Connection Verification", priority: "mandatory", testLevel: ["UI", "API", "WORDPRESS_E2E"] },
  { id: "F-487", module: 25, name: "Connection Disconnect", priority: "mandatory", testLevel: ["API", "PERSISTENCE", "WORDPRESS_E2E"] },
  { id: "F-488", module: 25, name: "Site Information", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-489", module: 25, name: "Site Health", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-490", module: 25, name: "Page CRUD", priority: "mandatory", testLevel: ["UI", "API", "PERSISTENCE"] },
  { id: "F-491", module: 25, name: "Page Duplicate", priority: "mandatory", testLevel: ["UI", "API", "PERSISTENCE"] },
  { id: "F-492", module: 25, name: "Page Reorder", priority: "mandatory", testLevel: ["UI", "API", "PERSISTENCE"] },
  { id: "F-493", module: 25, name: "Media Upload", priority: "mandatory", testLevel: ["UI", "API", "PERSISTENCE", "WORDPRESS_E2E"] },
  { id: "F-494", module: 25, name: "Media Management", priority: "mandatory", testLevel: ["UI", "API"] },
  { id: "F-495", module: 25, name: "Publish", priority: "mandatory", testLevel: ["UI", "API", "PERSISTENCE", "WORDPRESS_E2E"] },
  { id: "F-496", module: 25, name: "Publish Status", priority: "mandatory", testLevel: ["UI", "API"] },
  { id: "F-497", module: 25, name: "Publish Rollback", priority: "mandatory", testLevel: ["UI", "API", "PERSISTENCE"] },
  { id: "F-498", module: 25, name: "Publishing Jobs", priority: "mandatory", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-499", module: 25, name: "HTML Publishing", priority: "mandatory", testLevel: ["API", "UI"] },
  { id: "F-500", module: 25, name: "Gutenberg Block Publishing", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-501", module: 25, name: "Forms API", priority: "mandatory", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-502", module: 25, name: "SEO API", priority: "mandatory", testLevel: ["UI", "API"] },
  { id: "F-503", module: 25, name: "Analytics API", priority: "recommended", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-504", module: 25, name: "Menus API", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-505", module: 25, name: "Webhooks API", priority: "recommended", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-506", module: 25, name: "Plugins API", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-507", module: 25, name: "Themes API", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-508", module: 25, name: "Cache API", priority: "recommended", testLevel: ["API"] },

  // Module 26: WordPress Block Editor & Core Blocks (15 features)
  { id: "F-509", module: 26, name: "Core Paragraph Block", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-510", module: 26, name: "Core Heading Block", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-511", module: 26, name: "Core Image Block", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-512", module: 26, name: "Core List Block", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-513", module: 26, name: "Core Quote Block", priority: "recommended", testLevel: ["UI"] },
  { id: "F-514", module: 26, name: "Core Columns Block", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-515", module: 26, name: "Core Group Block", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-516", module: 26, name: "Block Attributes", priority: "recommended", testLevel: ["UI"] },
  { id: "F-517", module: 26, name: "Block Templates", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-518", module: 26, name: "Template Parts", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-519", module: 26, name: "Global Styles", priority: "recommended", testLevel: ["UI"] },
  { id: "F-520", module: 26, name: "Block Styles", priority: "recommended", testLevel: ["UI"] },
  { id: "F-521", module: 26, name: "Block Variations", priority: "recommended", testLevel: ["UI"] },
  { id: "F-522", module: 26, name: "Block Supports", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-523", module: 26, name: "Block Patterns", priority: "recommended", testLevel: ["UI"] },

  // Module 27: WordPress Content, Media & Taxonomy (17 features)
  { id: "F-524", module: 27, name: "Posts CRUD", priority: "mandatory", testLevel: ["UI", "API", "WORDPRESS_E2E"] },
  { id: "F-525", module: 27, name: "Post Revisions", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-526", module: 27, name: "Autosave", priority: "mandatory", testLevel: ["UI", "PERSISTENCE"] },
  { id: "F-527", module: 27, name: "Media Metadata", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-528", module: 27, name: "Responsive Image Sizes", priority: "recommended", testLevel: ["UI"] },
  { id: "F-529", module: 27, name: "Categories Taxonomy", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-530", module: 27, name: "Tags Taxonomy", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-531", module: 27, name: "Custom Taxonomies", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-532", module: 27, name: "CPT Registration", priority: "mandatory", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-533", module: 27, name: "CPT REST API Support", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-534", module: 27, name: "CPT Taxonomies", priority: "recommended", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-535", module: 27, name: "CPT Metadata", priority: "recommended", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-536", module: 27, name: "Comments Management", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-537", module: 27, name: "Post Formats", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-538", module: 27, name: "Featured Images", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-539", module: 27, name: "Excerpt Support", priority: "recommended", testLevel: ["UI"] },
  { id: "F-540", module: 27, name: "Post Statuses", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },

  // Module 28: WordPress APIs, Security & Extensibility (25 features)
  { id: "F-541", module: 28, name: "Metadata API", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-542", module: 28, name: "Options API", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-543", module: 28, name: "HTTP API", priority: "recommended", testLevel: ["API"] },
  { id: "F-544", module: 28, name: "REST API Infrastructure", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-545", module: 28, name: "Security Nonces", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-546", module: 28, name: "Sanitization & Escaping", priority: "mandatory", testLevel: ["UI", "API"] },
  { id: "F-547", module: 28, name: "User Authentication", priority: "mandatory", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-548", module: 28, name: "User Authorization & Roles", priority: "mandatory", testLevel: ["API"] },
  { id: "F-549", module: 28, name: "Password Hashing", priority: "mandatory", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-550", module: 28, name: "Secure Cookies", priority: "mandatory", testLevel: ["API"] },
  { id: "F-551", module: 28, name: "Application Passwords", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-552", module: 28, name: "Hooks & Actions System", priority: "recommended", testLevel: ["API"] },
  { id: "F-553", module: 28, name: "Filter System", priority: "recommended", testLevel: ["API"] },
  { id: "F-554", module: 28, name: "Database API & Abstraction", priority: "mandatory", testLevel: ["PERSISTENCE"] },
  { id: "F-555", module: 28, name: "Plugins API Core", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-556", module: 28, name: "Settings API Core", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-557", module: 28, name: "Shortcode API Engine", priority: "recommended", testLevel: ["UI"] },
  { id: "F-558", module: 28, name: "Site Health API", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-559", module: 28, name: "Theme API Core", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-560", module: 28, name: "Rewrite API", priority: "recommended", testLevel: ["API"] },
  { id: "F-561", module: 28, name: "Cron / Scheduling API", priority: "recommended", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-562", module: 28, name: "Transient Storage API", priority: "recommended", testLevel: ["API"] },
  { id: "F-563", module: 28, name: "Object Cache API", priority: "recommended", testLevel: ["API"] },
  { id: "F-564", module: 28, name: "XML-RPC Endpoint Handling", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-565", module: 28, name: "Embed / OEmbed Engine", priority: "recommended", testLevel: ["UI"] },

  // Module 29: WordPress Plugins, Themes & Settings (20 features)
  { id: "F-566", module: 29, name: "Plugin Installation", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-567", module: 29, name: "Plugin Activation/Deactivation", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-568", module: 29, name: "Plugin Dependencies", priority: "recommended", testLevel: ["API"] },
  { id: "F-569", module: 29, name: "Plugin Meta Info", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-570", module: 29, name: "Theme Installation", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-571", module: 29, name: "Theme Activation", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-572", module: 29, name: "Child Theme Support", priority: "recommended", testLevel: ["API"] },
  { id: "F-573", module: 29, name: "Theme Options", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-574", module: 29, name: "General Settings UI", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-575", module: 29, name: "Writing Settings", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-576", module: 29, name: "Reading Settings", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-577", module: 29, name: "Discussion Settings", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-578", module: 29, name: "Media Settings", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-579", module: 29, name: "Permalinks Settings", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-580", module: 29, name: "Custom Settings Pages", priority: "recommended", testLevel: ["API", "PERSISTENCE"] },
  { id: "F-581", module: 29, name: "Settings Section Registration", priority: "recommended", testLevel: ["UI"] },
  { id: "F-582", module: 29, name: "Settings Field Sanitization", priority: "mandatory", testLevel: ["UI", "API"] },
  { id: "F-583", module: 29, name: "Option Validation & Error Reporting", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-584", module: 29, name: "Widget Management", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-585", module: 29, name: "Customizer Integration", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },

  // Module 30: WordPress General, Privacy & Site Health (20 features)
  { id: "F-586", module: 30, name: "Site Title & Tagline Config", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-587", module: 30, name: "Admin Email Config", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-588", module: 30, name: "Timezone & Date Format", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-589", module: 30, name: "Homepage Display Settings", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-590", module: 30, name: "Search Engine Visibility Toggle", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-591", module: 30, name: "Site Health Status Scanner", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-592", module: 30, name: "Critical Issues Resolver", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-593", module: 30, name: "Site Health Info Report", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-594", module: 30, name: "Debug Info Exporter", priority: "recommended", testLevel: ["UI"] },
  { id: "F-595", module: 30, name: "Server Config Validator", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-596", module: 30, name: "PHP Version Checker", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-597", module: 30, name: "MySQL Version Checker", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-598", module: 30, name: "HTTPS Security Status", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-599", module: 30, name: "Directory Permissions Inspector", priority: "mandatory", testLevel: ["UI"] },
  { id: "F-600", module: 30, name: "REST API Availability Inspector", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-601", module: 30, name: "Loopback Request Inspector", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-602", module: 30, name: "Background Update Status", priority: "recommended", testLevel: ["UI"] },
  { id: "F-603", module: 30, name: "Theme/Plugin Update Checker", priority: "recommended", testLevel: ["UI"] },
  { id: "F-604", module: 30, name: "Database Connection Inspector", priority: "mandatory", testLevel: ["PERSISTENCE"] },
  { id: "F-605", module: 30, name: "SSL Certificate Validator", priority: "recommended", testLevel: ["UI"] },

  // Module 31: WordPress Permalinks, Privacy, Export & Multisite (15 features)
  { id: "F-606", module: 31, name: "Permalink Structures Engine", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-607", module: 31, name: "Post Name Permalinks", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-608", module: 31, name: "Custom Permalink Structure", priority: "mandatory", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-609", module: 31, name: "Category & Tag Bases", priority: "recommended", testLevel: ["UI", "WORDPRESS_E2E"] },
  { id: "F-610", module: 31, name: "Privacy Policy Page Manager", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-611", module: 31, name: "Personal Data Exporter", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-612", module: 31, name: "Personal Data Eraser", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-613", module: 31, name: "Privacy Request Handler", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-614", module: 31, name: "WordPress Content Exporter", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-615", module: 31, name: "WordPress Importer", priority: "mandatory", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-616", module: 31, name: "Multisite Network Support", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-617", module: 31, name: "Network Site Switcher", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-618", module: 31, name: "Domain Mapping", priority: "recommended", testLevel: ["UI", "PERSISTENCE"] },
  { id: "F-619", module: 31, name: "Network Plugins Manager", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] },
  { id: "F-620", module: 31, name: "Network Site Creation", priority: "recommended", testLevel: ["API", "WORDPRESS_E2E"] }
];

const targetPath = path.join(process.cwd(), "tests", "feature-registry", "part-b-modules-25-31.json");
fs.mkdirSync(path.dirname(targetPath), { recursive: true });
fs.writeFileSync(targetPath, JSON.stringify(registry, null, 2));

console.log(`Successfully generated registry with ${registry.length} features at ${targetPath}`);
console.log(`Mandatory count: ${registry.filter(f => f.priority === "mandatory").length}`);
console.log(`Recommended count: ${registry.filter(f => f.priority === "recommended").length}`);
