import { AppError } from "../utils/app-error.js";
import { canUserAccessResource } from "./permission.service.js";
import { purgeHostingCache, runSecurityAudit } from "./siteSecurity.service.js";
import { createBackupRecord, appendBackup } from "./backups/websiteBackup.service.js";
import { createStagingEnvironment } from "./staging.service.js";
import { getWebsiteById } from "./website.service.js";
import { recordAuditLog } from "./audit.service.js";
import { prisma } from "../config/prisma.js";

const db = prisma as any;

export type AiHostingToolAction = "cleanCache" | "createBackup" | "createStaging" | "runVulnerabilityScan";

export interface AiHostingToolResult {
  tool: AiHostingToolAction;
  success: boolean;
  message: string;
  data?: any;
  executedAt: string;
}

/**
 * Execute an authorized AI Hosting Assistant action safely.
 * F-479 (Hosting AI Assistant), F-480 (AI Clean Cache), F-481 (AI Create Backup),
 * F-482 (AI Create Staging), F-483 (AI Vulnerability Scan).
 */
export async function executeAiHostingTool(
  websiteId: string,
  userId: string,
  action: AiHostingToolAction,
  params?: Record<string, any>
): Promise<AiHostingToolResult> {
  const executedAt = new Date().toISOString();

  // 1. Authorize user permission
  const canEdit = await canUserAccessResource(userId, websiteId, "*", "EDIT");
  if (!canEdit) {
    throw new AppError("You do not have permission to execute hosting operations on this website.", 403, "FORBIDDEN");
  }

  const website = await getWebsiteById(websiteId, userId);

  let resultData: any = null;
  let message = "";

  switch (action) {
    case "cleanCache": {
      // F-480: AI Clean Cache
      const res = await purgeHostingCache(websiteId, userId);
      message = "AI Hosting Assistant purged edge cache successfully across all points of presence.";
      resultData = res;
      break;
    }
    case "createBackup": {
      // F-481: AI Create Backup
      const editorData: any = website.editorData || {};
      const backup = createBackupRecord(editorData, {
        trigger: "manual",
        label: params?.label || `AI Backup — ${new Date().toISOString().slice(0, 16)}`,
        notes: "Generated by AI Hosting Assistant",
      });
      const existingBackups = Array.isArray(editorData.backups) ? editorData.backups : [];
      const updatedList = appendBackup(existingBackups, backup);

      await db.website.update({
        where: { id: websiteId },
        data: {
          editorData: {
            ...editorData,
            backups: updatedList,
          },
        },
      });

      message = `AI Hosting Assistant created backup '${backup.label}' (${Math.round(backup.sizeBytes / 1024)} KB).`;
      resultData = backup;
      break;
    }
    case "createStaging": {
      // F-482: AI Create Staging
      const stagingInfo = await createStagingEnvironment(websiteId, userId);
      message = `AI Hosting Assistant created staging environment at ${stagingInfo.stagingUrl}`;
      resultData = stagingInfo;
      break;
    }
    case "runVulnerabilityScan": {
      // F-483: AI Vulnerability Scan
      const audit = await runSecurityAudit(websiteId, userId);
      message = `AI Hosting Assistant completed vulnerability scan. Health score: ${audit.score}/100 (${audit.status}). Found ${audit.findingsCount} issues.`;
      resultData = audit;
      break;
    }
    default:
      throw new AppError(`Unknown AI hosting action '${action}'`, 400, "BAD_REQUEST");
  }

  await recordAuditLog({
    userId,
    action: `AI_HOSTING_TOOL_${action.toUpperCase()}`,
    targetResource: `website:${websiteId}`,
    details: { action, params, resultData },
  });

  return {
    tool: action,
    success: true,
    message,
    data: resultData,
    executedAt,
  };
}
