import { Router } from "express";
import { requireAuth } from "../middlewares/auth.middleware.js";
import { authorizeCapability } from "../services/permission.service.js";
import { requireRuntimeCapability } from "../platform/control/runtime-capability.js";
import { applyAiChangesetHandler, cancelAiChangesetHandler, generateSiteHandler, getAiChangesetHandler, retryAiChangesetHandler } from "../controllers/ai.controller.js";
import { createDesignHandler, getDesignHandler, cancelDesignHandler, retryDesignHandler, designCapabilitiesHandler, getAiCreditBalanceHandler } from "../controllers/ai-design.controller.js";
const router = Router();
router.get("/capabilities", requireAuth, designCapabilitiesHandler);
router.get("/websites/:id/credits", requireAuth, authorizeCapability("VIEW"), getAiCreditBalanceHandler);
router.post("/websites/:id/executions", requireAuth, requireRuntimeCapability("stitch-design"), createDesignHandler);
router.get("/executions/:executionId", requireAuth, requireRuntimeCapability("stitch-design", { allowDegraded: true }), getDesignHandler);
router.post("/executions/:executionId/cancel", requireAuth, requireRuntimeCapability("stitch-design", { allowDegraded: true }), cancelDesignHandler);
router.post("/executions/:executionId/retry", requireAuth, requireRuntimeCapability("stitch-design"), retryDesignHandler);
router.post("/websites/:id/generate", requireAuth, authorizeCapability("EDIT_DESIGN"), generateSiteHandler);
router.get("/changesets/:changesetId", requireAuth, getAiChangesetHandler);
router.post("/changesets/:changesetId/apply", requireAuth, applyAiChangesetHandler);
router.post("/changesets/:changesetId/cancel", requireAuth, cancelAiChangesetHandler);
router.post("/changesets/:changesetId/retry", requireAuth, retryAiChangesetHandler);
export default router;
