export interface CountryData {
  iso: string;
  name: string;
  flag: string;
  dialCode: string;
  expectedDigits: number | number[]; // e.g. 10 or [9, 10]
  placeholder: string; // e.g. "Enter your 10-digit phone number"
  formatPattern?: string; // e.g. "##### #####" or "### ### ####"
}

export const COUNTRY_DATA: CountryData[] = [
  {
    iso: "IN",
    name: "India",
    flag: "🇮🇳",
    dialCode: "+91",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "##### #####",
  },
  {
    iso: "US",
    name: "United States",
    flag: "🇺🇸",
    dialCode: "+1",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "(###) ###-####",
  },
  {
    iso: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    dialCode: "+44",
    expectedDigits: [10, 11],
    placeholder: "Enter your phone number",
    formatPattern: "##### ######",
  },
  {
    iso: "CA",
    name: "Canada",
    flag: "🇨🇦",
    dialCode: "+1",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "(###) ###-####",
  },
  {
    iso: "AU",
    name: "Australia",
    flag: "🇦🇺",
    dialCode: "+61",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "### ### ###",
  },
  {
    iso: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    dialCode: "+971",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    dialCode: "+966",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "DE",
    name: "Germany",
    flag: "🇩🇪",
    dialCode: "+49",
    expectedDigits: [10, 11],
    placeholder: "Enter your phone number",
    formatPattern: "#### ########",
  },
  {
    iso: "FR",
    name: "France",
    flag: "🇫🇷",
    dialCode: "+33",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "# ## ## ## ##",
  },
  {
    iso: "JP",
    name: "Japan",
    flag: "🇯🇵",
    dialCode: "+81",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "## #### ####",
  },
  {
    iso: "CN",
    name: "China",
    flag: "🇨🇳",
    dialCode: "+86",
    expectedDigits: 11,
    placeholder: "Enter your 11-digit phone number",
    formatPattern: "### #### ####",
  },
  {
    iso: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    dialCode: "+55",
    expectedDigits: 11,
    placeholder: "Enter your 11-digit phone number",
    formatPattern: "## #####-####",
  },
  {
    iso: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    dialCode: "+65",
    expectedDigits: 8,
    placeholder: "Enter your 8-digit phone number",
    formatPattern: "#### ####",
  },
  {
    iso: "MY",
    name: "Malaysia",
    flag: "🇲🇾",
    dialCode: "+60",
    expectedDigits: [9, 10],
    placeholder: "Enter your phone number",
    formatPattern: "## #### ####",
  },
  {
    iso: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
    dialCode: "+62",
    expectedDigits: [10, 11, 12],
    placeholder: "Enter your phone number",
    formatPattern: "###-####-####",
  },
  {
    iso: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    dialCode: "+63",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ### ####",
  },
  {
    iso: "PK",
    name: "Pakistan",
    flag: "🇵🇰",
    dialCode: "+92",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### #######",
  },
  {
    iso: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    dialCode: "+880",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "####-######",
  },
  {
    iso: "LK",
    name: "Sri Lanka",
    flag: "🇱🇰",
    dialCode: "+94",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "NP",
    name: "Nepal",
    flag: "🇳🇵",
    dialCode: "+977",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "###-#######",
  },
  {
    iso: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    dialCode: "+27",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    dialCode: "+234",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ### ####",
  },
  {
    iso: "MX",
    name: "Mexico",
    flag: "🇲🇽",
    dialCode: "+52",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ### ####",
  },
  {
    iso: "IT",
    name: "Italy",
    flag: "🇮🇹",
    dialCode: "+39",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### #######",
  },
  {
    iso: "ES",
    name: "Spain",
    flag: "🇪🇸",
    dialCode: "+34",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "### ## ## ##",
  },
  {
    iso: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    dialCode: "+31",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "# ########",
  },
  {
    iso: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    dialCode: "+41",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ## ##",
  },
  {
    iso: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    dialCode: "+46",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ## ##",
  },
  {
    iso: "NO",
    name: "Norway",
    flag: "🇳🇴",
    dialCode: "+47",
    expectedDigits: 8,
    placeholder: "Enter your 8-digit phone number",
    formatPattern: "### ## ###",
  },
  {
    iso: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    dialCode: "+45",
    expectedDigits: 8,
    placeholder: "Enter your 8-digit phone number",
    formatPattern: "## ## ## ##",
  },
  {
    iso: "FI",
    name: "Finland",
    flag: "🇫🇮",
    dialCode: "+358",
    expectedDigits: [9, 10],
    placeholder: "Enter your phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    dialCode: "+64",
    expectedDigits: [8, 9],
    placeholder: "Enter your phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "KR",
    name: "South Korea",
    flag: "🇰🇷",
    dialCode: "+82",
    expectedDigits: [9, 10],
    placeholder: "Enter your phone number",
    formatPattern: "## #### ####",
  },
  {
    iso: "RU",
    name: "Russia",
    flag: "🇷🇺",
    dialCode: "+7",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ###-##-##",
  },
  {
    iso: "TR",
    name: "Turkey",
    flag: "🇹🇷",
    dialCode: "+90",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ### ## ##",
  },
  {
    iso: "EG",
    name: "Egypt",
    flag: "🇪🇬",
    dialCode: "+20",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "## #### ####",
  },
  {
    iso: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
    dialCode: "+84",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "### ### ###",
  },
  {
    iso: "TH",
    name: "Thailand",
    flag: "🇹🇭",
    dialCode: "+66",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    dialCode: "+54",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ###-####",
  },
  {
    iso: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    dialCode: "+57",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ### ####",
  },
  {
    iso: "CL",
    name: "Chile",
    flag: "🇨🇱",
    dialCode: "+56",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "# #### ####",
  },
  {
    iso: "PE",
    name: "Peru",
    flag: "🇵🇪",
    dialCode: "+51",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "### ### ###",
  },
  {
    iso: "IL",
    name: "Israel",
    flag: "🇮🇱",
    dialCode: "+972",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "##-###-####",
  },
  {
    iso: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    dialCode: "+353",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "## ### ####",
  },
  {
    iso: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    dialCode: "+351",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "### ### ###",
  },
  {
    iso: "GR",
    name: "Greece",
    flag: "🇬🇷",
    dialCode: "+30",
    expectedDigits: 10,
    placeholder: "Enter your 10-digit phone number",
    formatPattern: "### ### ####",
  },
  {
    iso: "PL",
    name: "Poland",
    flag: "🇵🇱",
    dialCode: "+48",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "### ### ###",
  },
  {
    iso: "AT",
    name: "Austria",
    flag: "🇦🇹",
    dialCode: "+43",
    expectedDigits: [10, 11],
    placeholder: "Enter your phone number",
    formatPattern: "#### ######",
  },
  {
    iso: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    dialCode: "+32",
    expectedDigits: 9,
    placeholder: "Enter your 9-digit phone number",
    formatPattern: "### ## ## ##",
  },
];

export const DEFAULT_COUNTRY: CountryData = COUNTRY_DATA[0]; // India
