import type {
  ElementType,
  EditorElement
} from "../types";
import { generateId } from "../utils";
import { getNavigationDefaultElement } from "../navigation/navigationDefaults";

// ==========================================
// ELEMENT DEFAULT INITIALIZERS & PRESET TEMPLATES
// ==========================================

// PRESET SECTION TEMPLATES
export const PRESET_SECTION_TEMPLATES: Record<
  string,
  { name: string; icon: string; description: string; getElements: (genId: () => string) => EditorElement }
> = {
  hero: {
    name: "Hero Section",
    icon: "✨",
    description: "Full-width hero header with title, subtitle & action buttons",
    getElements: (genId) => ({
      id: genId(),
      type: "container",
      content: "Hero Section",
      styles: {
        width: "100%",
        paddingTop: "48px",
        paddingRight: "24px",
        paddingBottom: "48px",
        paddingLeft: "24px",
        backgroundColor: "#f8fafc",
        borderRadius: "16px",
        marginTop: "16px",
        marginBottom: "16px",
        textAlign: "center",
      },
      children: [
        {
          id: genId(),
          type: "heading",
          content: "Build Extraordinary Web Experiences",
          headingLevel: "h1",
          styles: {
            fontSize: "2.25rem",
            color: "#0f172a",
            fontWeight: "800",
            marginBottom: "12px",
            textAlign: "center",
          },
        },
        {
          id: genId(),
          type: "text",
          content: "Create beautiful, high-converting websites in minutes with our intuitive visual site builder.",
          styles: {
            fontSize: "1.125rem",
            color: "#475569",
            marginBottom: "24px",
            textAlign: "center",
          },
        },
        {
          id: genId(),
          type: "button",
          content: "Get Started Free",
          href: "#",
          styles: {
            backgroundColor: "#6366f1",
            color: "#ffffff",
            paddingTop: "12px",
            paddingRight: "28px",
            paddingBottom: "12px",
            paddingLeft: "28px",
            borderRadius: "12px",
            fontWeight: "600",
            fontSize: "1rem",
            display: "inline-block",
          },
        },
      ],
    }),
  },
  features: {
    name: "Features Grid",
    icon: "📌",
    description: "Highlight key product features with structured card containers",
    getElements: (genId) => ({
      id: genId(),
      type: "container",
      content: "Features Grid",
      styles: {
        width: "100%",
        paddingTop: "40px",
        paddingRight: "24px",
        paddingBottom: "40px",
        paddingLeft: "24px",
        backgroundColor: "#ffffff",
        borderRadius: "16px",
        marginTop: "16px",
        marginBottom: "16px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderColor: "#e2e8f0",
      },
      children: [
        {
          id: genId(),
          type: "heading",
          content: "Everything You Need to Succeed",
          headingLevel: "h2",
          styles: {
            fontSize: "1.75rem",
            color: "#0f172a",
            fontWeight: "700",
            marginBottom: "24px",
            textAlign: "center",
          },
        },
        {
          id: genId(),
          type: "text",
          content: "Designed for speed, flexibility, and unmatched visual control.",
          styles: {
            fontSize: "1rem",
            color: "#64748b",
            marginBottom: "24px",
            textAlign: "center",
          },
        },
      ],
    }),
  },
  cta: {
    name: "Call to Action Banner",
    icon: "🚀",
    description: "High-impact conversion banner with gradient styling",
    getElements: (genId) => ({
      id: genId(),
      type: "call-to-action",
      content: "Ready to launch your project?",
      ctaTitle: "Ready to launch your next big idea?",
      ctaDescription: "Join thousands of creators building stunning web applications today.",
      ctaButtonText: "Start Building Now",
      ctaButtonUrl: "#",
      ctaBgColor: "#4f46e5",
      ctaTextColor: "#ffffff",
      ctaButtonBg: "#ffffff",
      ctaButtonTextColor: "#4f46e5",
      styles: {
        width: "100%",
        marginTop: "16px",
        marginBottom: "16px",
        borderRadius: "16px",
      },
    }),
  },
  testimonials: {
    name: "Testimonials Carousel",
    icon: "💬",
    description: "Social proof carousel featuring customer quotes and ratings",
    getElements: (genId) => ({
      id: genId(),
      type: "testimonial-carousel",
      content: "Customer Testimonials",
      testimonialItems: [
        {
          id: genId(),
          quote: "This editor changed how our team launches landing pages. Absolutely effortless!",
          name: "Sarah Jenkins",
          role: "Product Lead at Acme Inc.",
          rating: 5,
        },
        {
          id: genId(),
          quote: "The pre-built templates and custom widgets saved us hundreds of design hours.",
          name: "Alex Rivera",
          role: "Founder at GrowthFlow",
          rating: 5,
        },
      ],
      styles: {
        width: "100%",
        marginTop: "16px",
        marginBottom: "16px",
      },
    }),
  },
  pricing: {
    name: "Pricing Table Section",
    icon: "🏷️",
    description: "Tiered pricing table widget with feature lists and CTA buttons",
    getElements: (genId) => ({
      id: genId(),
      type: "price-table",
      content: "Pricing Tier",
      priceTitle: "Pro Plan",
      priceAmount: "$29",
      pricePeriod: "/ month",
      priceFeatures: [
        "Unlimited Landing Pages",
        "Custom Domain Support",
        "Advanced Analytics",
        "24/7 Priority Support",
      ],
      priceButtonText: "Choose Pro",
      priceButtonUrl: "#",
      priceIsFeatured: true,
      priceFeaturedLabel: "Most Popular",
      styles: {
        width: "100%",
        marginTop: "16px",
        marginBottom: "16px",
      },
    }),
  },
};


// DEFAULT ELEMENT FACTORY FUNCTION
export function createDefaultElement(type: ElementType): EditorElement {
  const id = generateId();
  const navDefault = getNavigationDefaultElement(type, id);
  if (navDefault) return navDefault;

  switch (type) {
    case "container":
      return {
        id,
        type: "container",
        content: "Container",
        children: [],
        layout: {
          direction: "column",
          justifyContent: "flex-start",
          alignItems: "stretch",
          gap: 10,
        },
        styles: {
          width: "100%",
          height: "auto",
          backgroundColor: "#ffffff",
          paddingTop: "16px",
          paddingRight: "16px",
          paddingBottom: "16px",
          paddingLeft: "16px",
          marginTop: "8px",
          marginBottom: "8px",
          borderRadius: "12px",
        },
      };
    case "heading":
      return {
        id,
        type: "heading",
        content: "Heading Text",
        styles: {
          color: "#0f172a",
          fontSize: "32px",
          fontWeight: "700",
          textAlign: "left",
          marginTop: "16px",
          marginBottom: "16px",
          lineHeight: "1.2",
        },
      };
    case "text":
      return {
        id,
        type: "text",
        content: "Click here to edit this paragraph text. Add your own description and details.",
        styles: {
          color: "#475569",
          fontSize: "16px",
          fontWeight: "400",
          textAlign: "left",
          marginTop: "12px",
          marginBottom: "12px",
          lineHeight: "1.6",
        },
      };
    case "video":
      return {
        id,
        type: "video",
        content: "Video Widget",
        src: "",
        videoPoster: "",
        videoControls: true,
        videoAutoplay: false,
        videoLoop: false,
        videoMuted: false,
        styles: {
          width: "100%",
          height: "auto",
          borderRadius: "8px",
          textAlign: "left",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "image":
      return {
        id,
        type: "image",
        content: "Image",
        src: "",
        alt: "Image description",
        styles: {
          width: "100%",
          height: "auto",
          borderRadius: "8px",
          objectFit: "cover",
          objectPosition: "center",
          opacity: 1,
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "button":
      return {
        id,
        type: "button",
        content: "Click Me",
        buttonText: "Click Me",
        href: "/",
        linkUrl: "/",
        destinationType: "page",
        linkType: "page",
        pageId: "home",
        target: "_self",
        styles: {
          color: "#ffffff",
          backgroundColor: "#2563eb",
          fontSize: "14px",
          fontWeight: "600",
          textAlign: "center",
          padding: "10px 22px",
          borderRadius: "8px",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "posts":
      return {
        id,
        type: "posts",
        content: "Blog Posts",
        postsColumns: 3,
        postsGap: 20,
        postsImageHeight: "180px",
        postsShowImage: true,
        postsShowDate: true,
        postsShowExcerpt: true,
        postsShowReadMore: true,
        postsAlignment: "left",
        posts: [
          {
            id: "post_1",
            title: "Getting Started with Modern Web Design",
            excerpt: "Discover essential techniques and best practices to craft beautiful, responsive web applications effortlessly.",
            date: "Sep 1, 2026",
            author: "Jane Doe",
            image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&auto=format&fit=crop&q=80",
            readMoreText: "Read Article →",
            readMoreUrl: "#",
          },
          {
            id: "post_2",
            title: "Mastering Design Systems & Components",
            excerpt: "Learn how to build reusable design tokens and layout grids that scale across team workflows.",
            date: "Aug 28, 2026",
            author: "Alex Smith",
            image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
            readMoreText: "Read Article →",
            readMoreUrl: "#",
          },
          {
            id: "post_3",
            title: "Optimizing Web Performance & SEO",
            excerpt: "Boost site load speed and search engine rankings with modern code-splitting and asset management.",
            date: "Aug 24, 2026",
            author: "Chris Lee",
            image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80",
            readMoreText: "Read Article →",
            readMoreUrl: "#",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "16px",
          paddingRight: "16px",
          paddingBottom: "16px",
          paddingLeft: "16px",
          backgroundColor: "transparent",
        },
      };
    case "loop-grid":
      return {
        id,
        type: "loop-grid",
        content: "Loop Grid",
        loopColumns: 3,
        loopGap: 24,
        paginationType: "none",
        queryPostType: "post",
        queryLimit: 6,
        queryOrderBy: "date",
        queryOrder: "desc",
        queryTaxonomy: "category",
        queryTerms: [],
        queryOffset: 0,
        queryExcludeCurrent: true,
        querySource: "custom",
        children: [
          {
            id: `${id}_card`,
            type: "container",
            content: "Card Template",
            layout: { direction: "column", gap: 12 },
            styles: {
              backgroundColor: "#ffffff",
              borderRadius: "16px",
              paddingTop: "20px",
              paddingRight: "20px",
              paddingBottom: "20px",
              paddingLeft: "20px",
              boxShadow: "0 4px 20px -2px rgba(0, 0, 0, 0.05)",
              borderWidth: "1px",
              borderColor: "#f1f5f9",
            },
            children: [
              {
                id: `${id}_img`,
                type: "image",
                content: "Featured Image",
                src: "{{post.featuredImage}}",
                styles: { width: "100%", height: "200px", objectFit: "cover", borderRadius: "12px" },
              },
              {
                id: `${id}_date_author`,
                type: "text",
                content: "{{post.date}} • By {{post.author}}",
                styles: { fontSize: "12px", color: "#64748b", fontWeight: "500" },
              },
              {
                id: `${id}_title`,
                type: "heading",
                content: "{{post.title}}",
                styles: { fontSize: "20px", fontWeight: "700", color: "#0f172a", marginTop: "4px", marginBottom: "8px" },
              },
              {
                id: `${id}_excerpt`,
                type: "text",
                content: "{{post.excerpt}}",
                styles: { fontSize: "14px", color: "#475569", lineHeight: "1.6", marginBottom: "12px" },
              },
              {
                id: `${id}_btn`,
                type: "button",
                content: "Read Article →",
                href: "/blog/{{post.slug}}",
                styles: {
                  backgroundColor: "#2563eb",
                  color: "#ffffff",
                  paddingTop: "8px",
                  paddingBottom: "8px",
                  paddingLeft: "16px",
                  paddingRight: "16px",
                  borderRadius: "8px",
                  fontSize: "13px",
                  fontWeight: "600",
                },
              },
            ],
          },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          backgroundColor: "transparent",
        },
      };
    case "share-buttons":
      return {
        id,
        type: "share-buttons",
        content: "Share Buttons",
        shareUrlSource: "current-page",
        shareUrl: "",
        shareText: "Check out this page!",
        shareHashtags: "ForgeStudio,WebsiteBuilder",
        shareLayout: "horizontal",
        shareAlignment: "left",
        shareGap: 10,
        shareShowLabels: true,
        shareButtonStyle: "brand",
        shareButtonSize: "md",
        shareNetworks: [
          { id: "net_1", network: "facebook", label: "Share", urlSource: "inherit" },
          { id: "net_2", network: "twitter", label: "Tweet", urlSource: "inherit" },
          { id: "net_3", network: "linkedin", label: "Share", urlSource: "inherit" },
          { id: "net_4", network: "whatsapp", label: "WhatsApp", urlSource: "inherit" },
          { id: "net_5", network: "email", label: "Email", urlSource: "inherit" },
          { id: "net_6", network: "copy", label: "Copy Link", urlSource: "inherit" },
        ],
        styles: {
          width: "100%",
          marginTop: "12px",
          marginBottom: "12px",
          paddingTop: "8px",
          paddingRight: "8px",
          paddingBottom: "8px",
          paddingLeft: "8px",
          backgroundColor: "transparent",
        },
      };
    case "rating":
      return {
        id,
        type: "rating",
        content: "Rating",
        styles: {
          ratingStarsCount: "5",
          ratingValue: "4.5",
          ratingColor: "#f59e0b",
          ratingSize: "20",
          textAlign: "left",
          marginTop: "12px",
          marginBottom: "12px",
        },
      };
    case "portfolio":
      return {
        id,
        type: "portfolio",
        content: "Portfolio Projects",
        portfolioColumns: 3,
        portfolioGap: 24,
        portfolioImageHeight: "240px",
        portfolioAlignment: "left",
        portfolioShowCategory: true,
        portfolioShowDescription: true,
        portfolioShowLink: true,
        portfolioItems: [
          {
            id: "port_1",
            title: "E-Commerce Mobile App",
            category: "Mobile App",
            description: "A sleek iOS and Android shopping platform featuring real-time inventory tracking and one-touch checkout.",
            image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format&fit=crop&q=80",
            url: "#",
          },
          {
            id: "port_2",
            title: "SaaS Analytics Dashboard",
            category: "Web Design",
            description: "Comprehensive admin portal providing interactive revenue charts, user cohort analysis, and export tools.",
            image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
            url: "#",
          },
          {
            id: "port_3",
            title: "Brand Identity System",
            category: "Branding",
            description: "Complete visual identity rebrand including typography guidelines, vector mark system, and collateral.",
            image: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=800&auto=format&fit=crop&q=80",
            url: "#",
          },
        ],
      };
    case "progress-bar":
      return {
        id,
        type: "progress-bar",
        content: "Progress Bar",
        styles: {
          progressPercent: "75",
          progressColor: "#3b82f6",
          progressLabel: "Task Completion",
          marginTop: "12px",
          marginBottom: "12px",
        },
      };
    case "counter":
      return {
        id,
        type: "counter",
        content: "Counter",
        styles: {
          counterStart: "0",
          counterEnd: "100",
          counterPrefix: "",
          counterSuffix: "%",
          counterDuration: "2000",
          color: "#2563eb",
          fontSize: "36px",
          fontWeight: "700",
          textAlign: "center",
          marginTop: "12px",
          marginBottom: "12px",
        },
      };
    case "html":
      return {
        id,
        type: "html",
        content: "<div style='padding:20px; background:#eff6ff; border-radius:8px; border:1px solid #bfdbfe;'><p style='margin:0; font-size:14px;'>Custom HTML Code</p></div>",
        styles: {
          marginTop: "12px",
          marginBottom: "12px",
        },
      };
    case "shortcode":
      return {
        id,
        type: "shortcode",
        content: "gallery id='1' columns='3'",
        styles: {
          marginTop: "12px",
          marginBottom: "12px",
        },
      };
    case "alert":
      return {
        id,
        type: "alert",
        content: "Attention! This is an important notification alert message block.",
        styles: {
          alertType: "info",
          alertDismissible: "true",
          marginTop: "12px",
          marginBottom: "12px",
        },
      };
    case "social-icons":
      return {
        id,
        type: "social-icons",
        content: "Social Icons",
        styles: {
          socialFacebook: "https://facebook.com",
          socialTwitter: "https://twitter.com",
          socialInstagram: "https://instagram.com",
          socialLinkedin: "https://linkedin.com",
          socialIconSize: "20",
          socialIconColor: "#475569",
          textAlign: "center",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "google-maps":
      return {
        id,
        type: "google-maps",
        content: "Google Map",
        src: "https://maps.google.com/maps?q=London&t=&z=13&ie=UTF8&iwloc=&output=embed",
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "16px",
          paddingRight: "16px",
          paddingBottom: "16px",
          paddingLeft: "16px",
          backgroundColor: "transparent",
        },
      };
    case "slides":
      return {
        id,
        type: "slides",
        content: "Slideshow Section",
        slidesActiveIndex: 0,
        slidesAutoplay: true,
        slidesAutoplayInterval: 4000,
        slidesTransition: "slide",
        slidesHeight: "450px",
        slidesAlignment: "center",
        slidesShowArrows: true,
        slidesShowDots: true,
        slidesItems: [
          {
            id: "slide_1",
            title: "Empower Your Digital Growth",
            description: "Build high-converting modern websites with intuitive drag and drop tools and responsive controls.",
            bgImage: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1600&auto=format&fit=crop&q=80",
            bgColor: "#1e1b4b",
            buttonText: "Explore Features",
            buttonUrl: "#",
          },
          {
            id: "slide_2",
            title: "Designed for High Performance",
            description: "Lightning-fast page load speeds, automatic SEO optimization, and flawless mobile experience.",
            bgImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&auto=format&fit=crop&q=80",
            bgColor: "#0f172a",
            buttonText: "Start Free Trial",
            buttonUrl: "#",
          },
          {
            id: "slide_3",
            title: "Seamless Team Collaboration",
            description: "Work together in real-time, manage brand components, and deploy updates instantly.",
            bgImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1600&auto=format&fit=crop&q=80",
            bgColor: "#111827",
            buttonText: "Contact Sales",
            buttonUrl: "#",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "form":
      return {
        id,
        type: "form",
        content: "Form Widget",
        formSubmitText: "Send Message",
        formSubmitSuccessMsg: "Thank you! Your message has been sent successfully.",
        formLayoutColumns: 2,
        formFieldGap: 16,
        formShowLabels: true,
        formSubmitBtnBg: "#2563eb",
        formSubmitBtnColor: "#ffffff",
        formSubmitBtnFullWidth: true,
        formFields: [
          {
            id: "field_1",
            type: "text",
            label: "Full Name",
            placeholder: "John Doe",
            required: true,
            width: "half",
          },
          {
            id: "field_2",
            type: "email",
            label: "Email Address",
            placeholder: "john@example.com",
            required: true,
            width: "half",
          },
          {
            id: "field_3",
            type: "tel",
            label: "Phone Number",
            placeholder: "+1 (555) 000-0000",
            required: false,
            width: "half",
          },
          {
            id: "field_4",
            type: "select",
            label: "Subject / Service",
            placeholder: "Select an option",
            options: ["General Inquiry", "Project Consultation", "Support / Help"],
            required: false,
            width: "half",
          },
          {
            id: "field_5",
            type: "textarea",
            label: "Your Message",
            placeholder: "How can we help you?",
            required: true,
            width: "full",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "login":
      return {
        id,
        type: "login",
        content: "Login Interface",
        loginTitle: "Welcome Back",
        loginSubtitle: "Sign in to your account to access your workspace.",
        loginEmailLabel: "Email Address",
        loginEmailPlaceholder: "name@example.com",
        loginPasswordLabel: "Password",
        loginPasswordPlaceholder: "••••••••",
        loginShowRememberMe: true,
        loginShowForgotPassword: true,
        loginForgotPasswordText: "Forgot password?",
        loginForgotPasswordUrl: "#",
        loginButtonText: "Sign In",
        loginButtonBg: "#2563eb",
        loginButtonColor: "#ffffff",
        loginCardBg: "#ffffff",
        loginCardBorder: "#f1f5f9",
        loginShowSocialButtons: true,
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "nav-menu":
      return {
        id,
        type: "nav-menu",
        content: "Navigation Menu",
        navLayout: "horizontal",
        navAlignment: "left",
        navGap: 24,
        navItemColor: "#334155",
        navItemHoverColor: "#2563eb",
        navItemActiveColor: "#2563eb",
        navItemBg: "transparent",
        navItemHoverBg: "rgba(241, 245, 249, 0.8)",
        navItemActiveBg: "rgba(239, 246, 255, 1)",
        navFontSize: "14px",
        navFontWeight: "600",
        navMenuItems: [
          { id: "1", label: "Home", url: "/", isActive: true },
          { id: "2", label: "About", url: "/about" },
          {
            id: "3",
            label: "Services",
            url: "/services",
            submenu: [
              { id: "s1", label: "Web Design", url: "/services/web-design" },
              { id: "s2", label: "App Development", url: "/services/app-dev" },
              { id: "s3", label: "SEO & Growth", url: "/services/seo" },
            ],
          },
          { id: "4", label: "Pricing", url: "/pricing" },
          { id: "5", label: "Contact", url: "/contact" },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "8px",
          paddingRight: "8px",
          paddingBottom: "8px",
          paddingLeft: "8px",
          backgroundColor: "transparent",
        },
      };
    case "animated-headline":
      return {
        id,
        type: "animated-headline",
        content: "Animated Headline",
        headlinePrefix: "Build Websites That Are",
        headlineAnimatedTexts: ["Stunning", "Blazing Fast", "Ultra Flexible", "Powerful"],
        headlineSuffix: "With ForgeStudio",
        headlineAnimationType: "typing",
        headlineAnimationSpeed: 2500,
        headlineHighlightColor: "#2563eb",
        headlineHighlightBg: "rgba(239, 246, 255, 1)",
        headlineTag: "h2",
        styles: {
          width: "100%",
          marginTop: "20px",
          marginBottom: "20px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          fontSize: "36px",
          fontWeight: "800",
          textAlign: "center",
          color: "#0f172a",
          backgroundColor: "transparent",
        },
      };
    case "price-table":
      return {
        id,
        type: "price-table",
        content: "Price Table",
        pricingColumns: 3,
        pricingGap: 24,
        pricingCardBg: "#ffffff",
        pricingCardBorder: "#e2e8f0",
        pricingHighlightColor: "#2563eb",
        pricingBtnBg: "#2563eb",
        pricingBtnColor: "#ffffff",
        pricingPlans: [
          {
            id: "1",
            name: "Starter",
            price: "$19",
            period: "/ month",
            description: "Essential tools for personal projects & freelancers.",
            isPopular: false,
            buttonText: "Get Started",
            buttonUrl: "#",
            features: [
              { id: "f1", text: "5 Projects included", included: true },
              { id: "f2", text: "10GB SSD Storage", included: true },
              { id: "f3", text: "Basic Analytics", included: true },
              { id: "f4", text: "Custom Domain", included: false },
              { id: "f5", text: "24/7 Dedicated Support", included: false },
            ],
          },
          {
            id: "2",
            name: "Professional",
            price: "$49",
            period: "/ month",
            description: "Best for growing teams & expanding SaaS startups.",
            isPopular: true,
            badgeText: "MOST POPULAR",
            buttonText: "Start Free Trial",
            buttonUrl: "#",
            features: [
              { id: "f1", text: "Unlimited Projects", included: true },
              { id: "f2", text: "100GB SSD Storage", included: true },
              { id: "f3", text: "Advanced Analytics & Reports", included: true },
              { id: "f4", text: "Custom Domain & SSL", included: true },
              { id: "f5", text: "Priority Support", included: true },
            ],
          },
          {
            id: "3",
            name: "Enterprise",
            price: "$99",
            period: "/ month",
            description: "Advanced security, custom SLA, and dedicated scale.",
            isPopular: false,
            buttonText: "Contact Sales",
            buttonUrl: "#",
            features: [
              { id: "f1", text: "Unlimited Everything", included: true },
              { id: "f2", text: "1TB High Speed Storage", included: true },
              { id: "f3", text: "Custom Analytics & Export", included: true },
              { id: "f4", text: "Multi-Region Cloud Hosting", included: true },
              { id: "f5", text: "24/7 Dedicated Account Manager", included: true },
            ],
          },
        ],
        styles: {
          width: "100%",
          marginTop: "24px",
          marginBottom: "24px",
          paddingTop: "16px",
          paddingRight: "16px",
          paddingBottom: "16px",
          paddingLeft: "16px",
          backgroundColor: "transparent",
        },
      };
    case "price-list":
      return {
        id,
        type: "price-list",
        content: "Price List",
        priceListGap: 20,
        priceListShowImages: true,
        priceListImageSize: 48,
        priceListSeparatorStyle: "dotted",
        priceListTitleColor: "#0f172a",
        priceListPriceColor: "#2563eb",
        priceListPriceBg: "#eff6ff",
        priceListItems: [
          {
            id: "1",
            name: "Signature Espresso Blend",
            price: "$4.50",
            description: "Freshly roasted double shot arabica blend with velvety microfoam.",
            imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=150&auto=format&fit=crop&q=80",
          },
          {
            id: "2",
            name: "Haircut & Precision Styling",
            price: "$35.00",
            description: "Precision scissor cut, wash, scalp massage, and hot towel finish.",
            imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=150&auto=format&fit=crop&q=80",
          },
          {
            id: "3",
            name: "Web Design & UX Sprint",
            price: "$499.00",
            description: "Custom responsive website design with SEO optimization & CMS integration.",
            imageUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80",
          },
          {
            id: "4",
            name: "Organic Facial Treatment",
            price: "$85.00",
            description: "Deep cleansing facial treatment with organic botanicals & anti-aging serum.",
            imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=150&auto=format&fit=crop&q=80",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "transparent",
        },
      };
    case "gallery":
      return {
        id,
        type: "gallery",
        content: "Gallery",
        galleryColumns: 3,
        galleryGap: 16,
        galleryAspectRatio: "square",
        galleryShowCaptions: true,
        galleryCaptionPosition: "overlay",
        galleryHoverEffect: "zoom",
        galleryBorderRadius: "16px",
        galleryImages: [
          {
            id: "1",
            url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80",
            caption: "Modern Minimalist Architecture",
            altText: "Modern Architecture",
          },
          {
            id: "2",
            url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
            caption: "Scandinavian Living Space",
            altText: "Interior Living Room",
          },
          {
            id: "3",
            url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80",
            caption: "Bright Collaborative Workspace",
            altText: "Office Workspace",
          },
          {
            id: "4",
            url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80",
            caption: "Glass Highrise Skyscraper",
            altText: "City Skyscraper",
          },
          {
            id: "5",
            url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
            caption: "Serene Alpine Lake Reflection",
            altText: "Alpine Nature Landscape",
          },
          {
            id: "6",
            url: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&auto=format&fit=crop&q=80",
            caption: "Botanical Plant Oasis",
            altText: "Green Botanical Decor",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "20px",
          marginBottom: "20px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "transparent",
        },
      };
    case "flip-box":
      return {
        id,
        type: "flip-box",
        content: "Flip Box",
        flipDirection: "flip-right",
        flipDuration: "0.6s",
        flipCardHeight: "320px",
        flipBorderRadius: "20px",
        flipFrontTitle: "Interactive Solutions",
        flipFrontDescription: "Hover or tap to flip card and explore custom features.",
        flipFrontIcon: "🚀",
        flipFrontImage: "",
        flipFrontBg: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
        flipFrontTextColor: "#ffffff",
        flipBackTitle: "Ready to Start?",
        flipBackDescription: "Join thousands of creators building high-converting websites.",
        flipBackBg: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)",
        flipBackTextColor: "#ffffff",
        flipBackBtnText: "Get Started Now",
        flipBackBtnUrl: "#",
        flipBackBtnBg: "#ffffff",
        flipBackBtnTextColor: "#4f46e5",
        flipIsFlippedManual: false,
        styles: {
          width: "100%",
          marginTop: "20px",
          marginBottom: "20px",
          paddingTop: "8px",
          paddingRight: "8px",
          paddingBottom: "8px",
          paddingLeft: "8px",
          backgroundColor: "transparent",
        },
      };
    case "call-to-action":
      return {
        id,
        type: "call-to-action",
        content: "Call to Action",
        ctaHeading: "Ready to Accelerate Your Growth?",
        ctaDescription: "Join over 10,000+ businesses using our platform to scale their online presence.",
        ctaButtonText: "Claim Your Free Trial →",
        ctaButtonUrl: "#",
        ctaButtonBg: "linear-gradient(135deg, #e11d48 0%, #be123c 100%)",
        ctaButtonTextColor: "#ffffff",
        ctaButtonBorderRadius: "12px",
        ctaIcon: "⚡",
        ctaImage: "",
        ctaLayout: "centered",
        ctaCardBg: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
        ctaCardBorderColor: "rgba(255, 255, 255, 0.1)",
        ctaCardBorderRadius: "24px",
        ctaTextColor: "#ffffff",
        styles: {
          width: "100%",
          marginTop: "24px",
          marginBottom: "24px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "transparent",
        },
      };
    case "media-carousel":
      return {
        id,
        type: "media-carousel",
        content: "Media Carousel",
        mediaCarouselSlidesPerView: 3,
        mediaCarouselGap: 16,
        mediaCarouselAutoplay: true,
        mediaCarouselAutoplaySpeed: 3500,
        mediaCarouselLoop: true,
        mediaCarouselShowNav: true,
        mediaCarouselShowDots: true,
        mediaCarouselAspectRatio: "landscape",
        mediaCarouselBorderRadius: "16px",
        mediaCarouselTransition: "slide",
        mediaCarouselTransitionSpeed: 500,
        mediaCarouselImageSizing: "cover",
        mediaCarouselCardBg: "#0f172a",
        mediaCarouselTextColor: "#ffffff",
        mediaCarouselItems: [
          {
            id: "1",
            type: "image",
            url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
            title: "Alpine Vista",
            caption: "Mountain Vista & Serene Lake",
            altText: "Mountain Lake",
          },
          {
            id: "2",
            type: "video",
            url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?w=800&auto=format&fit=crop&q=80",
            videoUrl: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            title: "Urban Showcase",
            caption: "4K Architectural Motion Video",
            altText: "Skyscraper Video",
          },
          {
            id: "3",
            type: "image",
            url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
            title: "Evergreen Forest",
            caption: "Mist Over Dense Evergreen Canopy",
            altText: "Forest Mist",
          },
          {
            id: "4",
            type: "video",
            url: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800&auto=format&fit=crop&q=80",
            videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            title: "Autumn Motion",
            caption: "Cinematic Seasonal Motion",
            altText: "Autumn Forest Video",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "20px",
          marginBottom: "20px",
          paddingTop: "8px",
          paddingRight: "8px",
          paddingBottom: "8px",
          paddingLeft: "8px",
          backgroundColor: "transparent",
        },
      };
    case "testimonial-carousel":
      return {
        id,
        type: "testimonial-carousel",
        content: "Testimonial Carousel",
        testimonialSlidesPerView: 2,
        testimonialGap: 20,
        testimonialAutoplay: true,
        testimonialAutoplaySpeed: 4000,
        testimonialLoop: true,
        testimonialShowNav: true,
        testimonialShowDots: true,
        testimonialCardBg: "#ffffff",
        testimonialCardBorderRadius: "16px",
        testimonialTextColor: "#1e293b",
        testimonialStarColor: "#f59e0b",
        testimonialItems: [
          {
            id: "1",
            quote: "ForgeStudio transformed how we launch client sites. What used to take weeks now takes hours with incredible quality!",
            name: "Sarah Jenkins",
            role: "VP of Product, TechScale Inc.",
            avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
            rating: 5,
          },
          {
            id: "2",
            quote: "The visual editor and element customization options are second to none. Our conversion rates increased by 42%.",
            name: "Marcus Vance",
            role: "Founder & CEO, GrowthFlow",
            avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
            rating: 5,
          },
          {
            id: "3",
            quote: "Extremely intuitive UI, lightning-fast rendering, and fantastic pre-built components. A absolute game changer!",
            name: "Elena Rostova",
            role: "Head of Design, Studio Craft",
            avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
            rating: 5,
          },
        ],
        styles: {
          width: "100%",
          marginTop: "24px",
          marginBottom: "24px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "transparent",
        },
      };
    case "nested-carousel":
      return {
        id,
        type: "nested-carousel",
        content: "Nested Carousel",
        nestedCarouselSlidesPerView: 1,
        nestedCarouselGap: 20,
        nestedCarouselAutoplay: true,
        nestedCarouselAutoplaySpeed: 5000,
        nestedCarouselLoop: true,
        nestedCarouselShowNav: true,
        nestedCarouselShowDots: true,
        nestedCarouselSlideBg: "#ffffff",
        nestedCarouselBorderRadius: "16px",
        children: [
          {
            id: generateId(),
            type: "container",
            content: "Slide 1 Container",
            layout: { direction: "column", justifyContent: "center", alignItems: "center", gap: 12 },
            styles: {
              width: "100%",
              backgroundColor: "#ffffff",
              paddingTop: "32px",
              paddingRight: "32px",
              paddingBottom: "32px",
              paddingLeft: "32px",
              borderRadius: "16px",
              boxShadow: "0 10px 25px -5px rgba(0,0,0,0.05)",
              borderWidth: "1px",
              borderStyle: "solid",
              borderColor: "#e2e8f0",
            },
            children: [
              {
                id: generateId(),
                type: "heading",
                content: "🚀 Welcome to Nested Carousel",
                styles: { fontSize: "26px", fontWeight: "800", color: "#0f172a", textAlign: "center" },
              },
              {
                id: generateId(),
                type: "text",
                content: "Drop any widget inside this slide container. Combine text, headings, buttons, images, CTAs, forms, and more!",
                styles: { fontSize: "15px", color: "#64748b", textAlign: "center", marginTop: "8px" },
              },
              {
                id: generateId(),
                type: "button",
                content: "Get Started Now →",
                styles: { backgroundColor: "#6366f1", color: "#ffffff", paddingTop: "10px", paddingRight: "20px", paddingBottom: "10px", paddingLeft: "20px", borderRadius: "8px", fontWeight: "600", marginTop: "16px" },
              },
            ],
          },
          {
            id: generateId(),
            type: "container",
            content: "Slide 2 Container",
            layout: { direction: "column", justifyContent: "center", alignItems: "center", gap: 12 },
            styles: {
              width: "100%",
              backgroundColor: "#f8fafc",
              paddingTop: "32px",
              paddingRight: "32px",
              paddingBottom: "32px",
              paddingLeft: "32px",
              borderRadius: "16px",
              boxShadow: "0 10px 25px -5px rgba(0,0,0,0.05)",
              borderWidth: "1px",
              borderStyle: "solid",
              borderColor: "#e2e8f0",
            },
            children: [
              {
                id: generateId(),
                type: "heading",
                content: "⚡ Unlimited Design Flexibility",
                styles: { fontSize: "26px", fontWeight: "800", color: "#0f172a", textAlign: "center" },
              },
              {
                id: generateId(),
                type: "text",
                content: "Each slide is a full container widget capable of holding complex nested components.",
                styles: { fontSize: "15px", color: "#64748b", textAlign: "center", marginTop: "8px" },
              },
              {
                id: generateId(),
                type: "button",
                content: "Explore Features ➔",
                styles: { backgroundColor: "#0f172a", color: "#ffffff", paddingTop: "10px", paddingRight: "20px", paddingBottom: "10px", paddingLeft: "20px", borderRadius: "8px", fontWeight: "600", marginTop: "16px" },
              },
            ],
          },
          {
            id: generateId(),
            type: "container",
            content: "Slide 3 Container",
            layout: { direction: "column", justifyContent: "center", alignItems: "center", gap: 12 },
            styles: {
              width: "100%",
              backgroundColor: "#ffffff",
              paddingTop: "32px",
              paddingRight: "32px",
              paddingBottom: "32px",
              paddingLeft: "32px",
              borderRadius: "16px",
              boxShadow: "0 10px 25px -5px rgba(0,0,0,0.05)",
              borderWidth: "1px",
              borderStyle: "solid",
              borderColor: "#e2e8f0",
            },
            children: [
              {
                id: generateId(),
                type: "heading",
                content: "🎯 Convert Visitors Into Customers",
                styles: { fontSize: "26px", fontWeight: "800", color: "#0f172a", textAlign: "center" },
              },
              {
                id: generateId(),
                type: "text",
                content: "Engage your audience with interactive, conversion-focused slide layouts.",
                styles: { fontSize: "15px", color: "#64748b", textAlign: "center", marginTop: "8px" },
              },
              {
                id: generateId(),
                type: "button",
                content: "Start Free Trial",
                styles: { backgroundColor: "#10b981", color: "#ffffff", paddingTop: "10px", paddingRight: "20px", paddingBottom: "10px", paddingLeft: "20px", borderRadius: "8px", fontWeight: "600", marginTop: "16px" },
              },
            ],
          },
        ],
        styles: {
          width: "100%",
          marginTop: "24px",
          marginBottom: "24px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "transparent",
        },
      };
    case "loop-carousel":
      return {
        id,
        type: "loop-carousel",
        content: "Loop Carousel",
        loopCarouselSlidesPerView: 3,
        loopCarouselGap: 20,
        loopCarouselAutoplay: true,
        loopCarouselAutoplaySpeed: 3500,
        loopCarouselLoop: true,
        loopCarouselShowNav: true,
        loopCarouselShowDots: true,
        loopCarouselTransition: "slide",
        loopCarouselCardBg: "#ffffff",
        loopCarouselBorderRadius: "16px",
        loopCarouselTextColor: "#1e293b",
        loopCarouselItems: [
          {
            id: "1",
            title: "🌟 AI Assistant Studio",
            description: "Automate your workflows with smart AI-driven content & design generation.",
            badge: "NEW RELEASE",
            imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
            buttonText: "Try Assistant →",
            linkUrl: "#",
          },
          {
            id: "2",
            title: "⚡ Live Growth Analytics",
            description: "Monitor real-time visitors, engagement metrics, and funnel conversion stats.",
            badge: "POPULAR",
            imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
            buttonText: "View Analytics",
            linkUrl: "#",
          },
          {
            id: "3",
            title: "🎨 Modular Component System",
            description: "Build landing pages faster with 100+ pre-designed responsive blocks.",
            badge: "PRO WIDGET",
            imageUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80",
            buttonText: "Explore Library",
            linkUrl: "#",
          },
          {
            id: "4",
            title: "🔒 Enterprise Guard",
            description: "Bank-grade encryption, zero-downtime architecture, and SSL security.",
            badge: "SECURITY",
            imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
            buttonText: "Learn Security",
            linkUrl: "#",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "24px",
          marginBottom: "24px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "transparent",
        },
      };
    case "table-of-contents":
      return {
        id,
        type: "table-of-contents",
        content: "Table of Contents",
        tocTitle: "Table of Contents",
        tocShowTitle: true,
        tocIncludedLevels: ["h1", "h2", "h3", "h4", "h5", "h6"] as ("h1" | "h2" | "h3" | "h4" | "h5" | "h6")[],
        tocIndentPerLevel: 14,
        tocItemGap: 8,
        tocMarkerStyle: "bullet" as const,
        tocCardBg: "#f8fafc",
        tocBorderColor: "#e2e8f0",
        tocTextColor: "#334155",
        tocHoverColor: "#2563eb",
        tocTitleColor: "#0f172a",
        tocAlignment: "left" as const,
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "countdown":
      return {
        id,
        type: "countdown",
        content: "Countdown Timer",
        countdownTargetDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 16),
        countdownShowDays: true,
        countdownShowHours: true,
        countdownShowMinutes: true,
        countdownShowSeconds: true,
        countdownExpiredMessage: "Event Has Ended!",
        countdownAlignment: "center" as const,
        countdownGap: 16,
        countdownBoxBg: "#ffffff",
        countdownBoxBorder: "#e2e8f0",
        countdownBoxRadius: "16px",
        countdownNumberColor: "#0f172a",
        countdownNumberSize: "32px",
        countdownLabelColor: "#64748b",
        countdownLabelSize: "11px",
        countdownLabelTransform: "uppercase" as const,
        countdownDaysLabel: "Days",
        countdownHoursLabel: "Hours",
        countdownMinutesLabel: "Minutes",
        countdownSecondsLabel: "Seconds",
        styles: {
          width: "100%",
          marginTop: "20px",
          marginBottom: "20px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "facebook-page":
      return {
        id,
        type: "facebook-page",
        content: "Facebook Page",
        facebookPageUrl: "https://www.facebook.com/facebook",
        facebookTabs: "timeline",
        facebookWidth: 340,
        facebookHeight: 500,
        facebookSmallHeader: false,
        facebookAdaptContainerWidth: true,
        facebookHideCover: false,
        facebookShowFacepile: true,
        facebookAlignment: "center" as const,
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "blockquote":
      return {
        id,
        type: "blockquote",
        content: "The only way to do great work is to love what you do.",
        quoteAuthor: "Steve Jobs",
        quoteCitation: "Co-founder, Apple Inc.",
        quoteAlignment: "left" as const,
        quoteStyle: "accent-left" as const,
        quoteShowIcon: true,
        quoteIconColor: "#6366f1",
        quoteTextColor: "#1e293b",
        quoteTextSize: "1.125rem",
        quoteTextStyle: "italic" as const,
        quoteAuthorColor: "#475569",
        quoteAuthorSize: "0.875rem",
        quoteCardBg: "#f8fafc",
        quoteBorderColor: "#6366f1",
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "template":
      return {
        id,
        type: "template",
        content: "Reusable Template",
        templateSource: "preset" as const,
        templatePresetName: "hero" as const,
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "reviews":
      return {
        id,
        type: "reviews",
        content: "Customer Reviews",
        reviewLayout: "grid" as const,
        reviewColumns: 3,
        reviewAlignment: "left" as const,
        reviewStarColor: "#f59e0b",
        reviewCardBg: "#ffffff",
        reviewBorderColor: "#e2e8f0",
        reviewShowAvatar: true,
        reviewShowVerified: true,
        reviewItems: [
          {
            id: "rev-1",
            reviewerName: "Emily Watson",
            reviewerTitle: "Verified Buyer",
            reviewText: "Outstanding product quality! The interface is so intuitive and boosted our conversion rate significantly.",
            rating: 5,
            avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
            verified: true,
          },
          {
            id: "rev-2",
            reviewerName: "Marcus Vance",
            reviewerTitle: "Design Director",
            reviewText: "Incredible attention to detail. The customizable widgets and modern templates saved us weeks of dev time.",
            rating: 5,
            avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
            verified: true,
          },
          {
            id: "rev-3",
            reviewerName: "Sophia Chen",
            reviewerTitle: "SaaS Founder",
            reviewText: "Hands down the best site builder experience. Customer support is lightning fast and helpful!",
            rating: 5,
            avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
            verified: true,
          },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "facebook-button":
      return {
        id,
        type: "facebook-button",
        content: "Facebook Button",
        fbButtonUrl: "https://facebook.com",
        fbButtonLabel: "Like Us on Facebook",
        fbButtonAction: "like",
        fbButtonSize: "md",
        fbButtonAlignment: "left",
        fbButtonBgColor: "#1877F2",
        fbButtonTextColor: "#ffffff",
        fbButtonHoverBgColor: "#0d65d9",
        styles: {
          width: "auto",
          marginTop: "8px",
          marginBottom: "8px",
          paddingTop: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          backgroundColor: "transparent",
        },
      };
    case "facebook-embed":
      return {
        id,
        type: "facebook-embed",
        content: "Facebook Embed",
        fbEmbedUrl: "https://www.facebook.com/facebook",
        fbEmbedWidth: "100%",
        fbEmbedHeight: "450px",
        fbEmbedAlignment: "center",
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "facebook-comments":
      return {
        id,
        type: "facebook-comments",
        content: "Facebook Comments",
        fbCommentsUrl: "https://facebook.com",
        fbCommentsNumPosts: 5,
        fbCommentsWidth: "100%",
        fbCommentsAlignment: "center",
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "paypal-button":
      return {
        id,
        type: "paypal-button",
        content: "PayPal Button",
        paypalText: "Pay Now with PayPal",
        paypalAmount: "19.99",
        paypalCurrency: "USD",
        paypalItemName: "Digital Product",
        paypalItemDescription: "Instant access to digital downloads & platform features",
        paypalItemImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
        paypalQuantity: 1,
        paypalEnv: "sandbox",
        paypalButtonStyle: "custom",
        paypalButtonShape: "pill",
        paypalLayout: "horizontal",
        paypalButtonType: "checkout",
        paypalButtonSize: "md",
        paypalAlignment: "left",
        paypalBgColor: "#FFC439",
        paypalTextColor: "#003087",
        paypalHoverBgColor: "#f2b522",
        paypalSuccessAction: "message",
        paypalSuccessMessage: "🎉 Payment received! Thank you for your order.",
        paypalSuccessRedirectUrl: "https://example.com/thank-you",
        paypalCancelMessage: "Payment was cancelled. You can retry whenever you are ready.",
        styles: {
          marginTop: "8px",
          marginBottom: "8px",
        },
      };
    case "stripe-button":
      return {
        id,
        type: "stripe-button",
        content: "Stripe Button",
        stripeText: "Checkout with Stripe",
        stripeCheckoutUrl: "https://buy.stripe.com",
        stripeAmount: "$49.00",
        stripeButtonSize: "md",
        stripeAlignment: "left",
        stripeBgColor: "#635BFF",
        stripeTextColor: "#ffffff",
        stripeHoverBgColor: "#4b45e4",
        styles: {
          marginTop: "8px",
          marginBottom: "8px",
        },
      };
    case "lottie":
      return {
        id,
        type: "lottie",
        content: "Lottie Animation",
        lottieUrl: "https://assets9.lottiefiles.com/packages/lf20_9844-loading.json",
        lottieAutoplay: true,
        lottieLoop: true,
        lottieSpeed: 1,
        lottieWidth: "280px",
        lottieHeight: "280px",
        lottieAlignment: "center",
        styles: {
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "code-highlight":
      return {
        id,
        type: "code-highlight",
        content: "Code Highlight",
        codeSnippet: `// Welcome to ForgeStudio Code Highlight\nfunction greet(name: string): string {\n  return \`Hello, \${name}!\`;\n}\n\nconsole.log(greet("Developer"));`,
        codeLanguage: "typescript",
        codeShowLineNumbers: true,
        codeTheme: "dark",
        codeFontSize: "0.85rem",
        codeAlignment: "left",
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "video-playlist":
      return {
        id,
        type: "video-playlist",
        content: "Video Playlist",
        playlistActiveId: "1",
        playlistPosition: "right",
        playlistPlayerWidth: "65%",
        playlistAlignment: "left",
        playlistItems: [
          {
            id: "1",
            title: "ForgeStudio Platform Overview & Quick Start Guide",
            url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            duration: "3:45",
            thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80",
            thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80",
          },
          {
            id: "2",
            title: "Designing Responsive SaaS Layouts in Record Time",
            url: "https://vimeo.com/76979871",
            videoUrl: "https://vimeo.com/76979871",
            duration: "5:12",
            thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=400&q=80",
            thumbnailUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=400&q=80",
          },
        ],
        styles: {
          width: "100%",
          borderRadius: "12px",
          textAlign: "left",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "image-carousel":
      return {
        id,
        type: "image-carousel",
        content: "Image Carousel",
        imageCarouselItems: [
          {
            id: "img_slide_1",
            url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
            alt: "Modern Abstract Visual Art",
            caption: "Abstract Vibrant Geometry",
            title: "Modern Visuals",
          },
          {
            id: "img_slide_2",
            url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
            alt: "Minimalist SaaS Workspace",
            caption: "Clean Digital Workspaces",
            title: "Digital Workspace",
          },
          {
            id: "img_slide_3",
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
            alt: "Creative Micro-Interactions",
            caption: "Dynamic Responsive Motion",
            title: "Responsive Motion",
          },
          {
            id: "img_slide_4",
            url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80",
            alt: "Collaborative Team Ecosystem",
            caption: "Collaborative Product Design",
            title: "Team Ecosystem",
          },
        ],
        imageCarouselSlidesPerView: 3,
        imageCarouselGap: 16,
        imageCarouselAutoplay: true,
        imageCarouselAutoplaySpeed: 3000,
        imageCarouselLoop: true,
        imageCarouselShowNav: true,
        imageCarouselShowDots: true,
        imageCarouselTransition: "slide",
        imageCarouselImageSizing: "cover",
        imageCarouselHeight: "320px",
        imageCarouselAlignment: "center",
        imageCarouselBorderRadius: "16px",
        imageCarouselAspectRatio: "landscape",
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "transparent",
        },
      };
    case "mega-menu":
      return {
        id,
        type: "mega-menu",
        content: "Mega Menu Navigation",
        megaMenuBgColor: "#ffffff",
        megaMenuTextColor: "#0f172a",
        megaMenuAlignment: "center",
        styles: {
          width: "100%",
          marginTop: "8px",
          marginBottom: "8px",
        },
      };
    case "off-canvas":
      return {
        id,
        type: "off-canvas",
        content: "Off Canvas Panel",
        offCanvasButtonText: "Open Panel",
        offCanvasTitle: "Navigation & Quick Tools",
        offCanvasPosition: "right",
        offCanvasWidth: "340px",
        offCanvasOverlay: true,
        offCanvasButtonBgColor: "#0f172a",
        offCanvasButtonTextColor: "#ffffff",
        offCanvasPanelBgColor: "#ffffff",
        children: [],
        styles: {
          width: "auto",
          marginTop: "8px",
          marginBottom: "8px",
        },
      };
    case "basic-media-carousel":
      return {
        id,
        type: "basic-media-carousel",
        content: "Basic Media Carousel",
        mediaCarouselSlidesPerView: 2,
        mediaCarouselGap: 12,
        mediaCarouselAutoplay: true,
        mediaCarouselAutoplaySpeed: 3000,
        mediaCarouselLoop: true,
        mediaCarouselShowNav: true,
        mediaCarouselShowDots: true,
        mediaCarouselAspectRatio: "landscape",
        mediaCarouselBorderRadius: "12px",
        mediaCarouselTransition: "slide",
        mediaCarouselTransitionSpeed: 400,
        mediaCarouselImageSizing: "cover",
        mediaCarouselCardBg: "#ffffff",
        mediaCarouselItems: [
          {
            id: "bmc-1",
            type: "image",
            url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
            title: "Alpine Landscape",
            caption: "Mountain and lake view",
            altText: "Mountain Lake",
          },
          {
            id: "bmc-2",
            type: "video",
            url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?w=800&auto=format&fit=crop&q=80",
            videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            title: "Feature Showcase Video",
            caption: "Watch platform demo",
            altText: "Demo Video",
          },
          {
            id: "bmc-3",
            type: "image",
            url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
            title: "Digital Art Motion",
            caption: "Creative visual showcase",
            altText: "Visual Art",
          },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "basic-gallery":
      return {
        id,
        type: "basic-gallery",
        content: "Basic Gallery",
        basicGalleryColumns: 3,
        basicGalleryGap: 12,
        basicGalleryImageSizing: "cover",
        basicGalleryAlignment: "center",
        basicGalleryBorderRadius: "12px",
        basicGalleryImages: [
          { id: "bg-1", url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80", caption: "Modern Architecture" },
          { id: "bg-2", url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80", caption: "Scandinavian Interior" },
          { id: "bg-3", url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80", caption: "Bright Workspace" },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "audio-playlist":
      return {
        id,
        type: "audio-playlist",
        content: "Audio Playlist",
        audioPlaylistActiveId: "tr-1",
        audioPlaylistAutoPlay: false,
        audioPlaylistLoop: true,
        audioPlaylistVolume: 0.8,
        audioPlaylistCardBg: "#0f172a",
        audioPlaylistTextColor: "#ffffff",
        audioPlaylistAccentColor: "#38bdf8",
        audioPlaylistTracks: [
          { id: "tr-1", title: "01. Ambient Solar Echoes", artist: "ForgeStudio Soundscapes", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", duration: "06:12" },
          { id: "tr-2", title: "02. Deep Focus Flow", artist: "Acoustic Frequency Labs", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", duration: "07:05" },
          { id: "tr-3", title: "03. Midnight Synthesizer", artist: "Cybernetic Wave", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", duration: "05:48" },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "dynamic-lightbox":
      return {
        id,
        type: "dynamic-lightbox",
        content: "Dynamic Lightbox",
        lightboxTriggerText: "🔍 Open Media Showcase",
        lightboxTriggerStyle: "button",
        lightboxAnimation: "zoom",
        lightboxAnimationDuration: 300,
        lightboxMaxWidth: "900px",
        lightboxOverlayBg: "rgba(15, 23, 42, 0.9)",
        lightboxItems: [
          { id: "dl-1", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80", caption: "Serene Alpine Mountain Reflections", altText: "Alpine Mountain" },
          { id: "dl-2", url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80", caption: "Minimalist Modern Glass Architecture", altText: "Modern Glass Building" },
          { id: "dl-3", url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80", caption: "Dynamic Vibrant Digital Art Motion", altText: "Digital Art" },
        ],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "custom-svg":
      return {
        id,
        type: "custom-svg",
        content: "SVG / Custom Icon",
        svgRawContent: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>`,
        svgWidth: "64px",
        svgHeight: "64px",
        svgColor: "#0284c7",
        svgAlignment: "center",
        styles: {
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "icon-library":
      return {
        id,
        type: "icon-library",
        content: "Icon Library",
        iconName: "sparkles",
        iconCategory: "Interactive",
        iconSize: 48,
        iconColor: "#e11d48",
        iconAlignment: "center",
        iconBgColor: "#ffe4e6",
        iconBorderRadius: "12px",
        iconPadding: 16,
        styles: {
          marginTop: "16px",
          marginBottom: "16px",
        },
      };
    case "wc-product-title":
      return {
        id,
        type,
        content: "Sample Product Title",
        styles: { fontSize: "24px", fontWeight: "700", color: "#0f172a", marginBottom: "8px" }
      };
    case "wc-product-price":
      return {
        id,
        type,
        content: "$99.99",
        styles: { fontSize: "20px", fontWeight: "600", color: "#16a34a", marginBottom: "12px" }
      };
    case "wc-product-images":
      return {
        id,
        type,
        content: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
        styles: { width: "100%", borderRadius: "8px", marginBottom: "12px" }
      };
    case "wc-add-to-cart":
      return {
        id,
        type,
        content: "Add to Cart 🛒",
        styles: { backgroundColor: "#0f172a", color: "#ffffff", padding: "12px 24px", borderRadius: "8px", fontWeight: "600" }
      };
    case "wc-product-rating":
      return {
        id,
        type,
        content: "5",
        styles: { color: "#eab308", fontSize: "18px", marginBottom: "8px" }
      };

    case "price-table":
      return {
        id,
        type: "price-table",
        content: "Price Table",
        pricingColumns: 3,
        pricingGap: 24,
        pricingAlignment: "center",
        pricingCardBg: "#ffffff",
        pricingCardBorder: "#e2e8f0",
        pricingCardRadius: "16px",
        pricingHighlightColor: "#2563eb",
        pricingBtnBg: "#2563eb",
        pricingBtnColor: "#ffffff",
        pricingBtnHoverBg: "#1d4ed8",
        pricingBtnHoverColor: "#ffffff",
        pricingPlans: [
          {
            id: `plan_starter_${Date.now()}`,
            name: "Starter",
            price: "19",
            currency: "$",
            period: "/ month",
            description: "Essential tools for individuals & freelancers.",
            isPopular: false,
            isRecommended: false,
            badgeText: "BASIC",
            showBadge: false,
            buttonText: "Start Free Trial",
            buttonUrl: "#",
            buttonAlignment: "full",
            buttonWidth: "full",
            features: [
              { id: "f1", text: "Up to 5 Projects", included: true },
              { id: "f2", text: "Basic Analytics", included: true },
              { id: "f3", text: "24/7 Community Support", included: true },
              { id: "f4", text: "Custom Domain Integration", included: false },
              { id: "f5", text: "Dedicated Account Manager", included: false },
            ],
          },
          {
            id: `plan_pro_${Date.now() + 1}`,
            name: "Professional",
            price: "49",
            currency: "$",
            period: "/ month",
            description: "Powerful features for growing teams & startups.",
            isPopular: true,
            isRecommended: true,
            badgeText: "MOST POPULAR",
            showBadge: true,
            buttonText: "Get Pro Now",
            buttonUrl: "#",
            buttonAlignment: "full",
            buttonWidth: "full",
            features: [
              { id: "f1", text: "Unlimited Projects", included: true },
              { id: "f2", text: "Advanced Analytics & Reports", included: true },
              { id: "f3", text: "Priority Email & Chat Support", included: true },
              { id: "f4", text: "Custom Domain Integration", included: true },
              { id: "f5", text: "Dedicated Account Manager", included: false },
            ],
          },
          {
            id: `plan_enterprise_${Date.now() + 2}`,
            name: "Enterprise",
            price: "99",
            currency: "$",
            period: "/ month",
            description: "Tailored infrastructure for large organizations.",
            isPopular: false,
            isRecommended: false,
            badgeText: "BEST VALUE",
            showBadge: false,
            buttonText: "Contact Sales",
            buttonUrl: "#",
            buttonAlignment: "full",
            buttonWidth: "full",
            features: [
              { id: "f1", text: "Unlimited Projects & Workspaces", included: true },
              { id: "f2", text: "Custom BI Analytics & Exports", included: true },
              { id: "f3", text: "24/7 Phone & Dedicated Manager", included: true },
              { id: "f4", text: "Custom Domain & SSL Certificates", included: true },
              { id: "f5", text: "Custom SLA & Security Audit", included: true },
            ],
          },
        ],
        styles: {
          marginTop: "24px",
          marginBottom: "24px",
          paddingTop: "16px",
          paddingRight: "16px",
          paddingBottom: "16px",
          paddingLeft: "16px",
        },
      };

    case "nested-tabs":
      return {
        id,
        type: "nested-tabs",
        content: "Nested Tabs Container",
        tabsOrientation: "horizontal",
        tabsActiveIndex: 0,
        tabsItems: [
          { id: `tab_${Date.now()}_1`, title: "Tab 1", icon: "layers" },
          { id: `tab_${Date.now()}_2`, title: "Tab 2", icon: "sparkles" },
          { id: `tab_${Date.now()}_3`, title: "Tab 3", icon: "settings" },
        ],
        children: [],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "16px",
          paddingRight: "16px",
          paddingBottom: "16px",
          paddingLeft: "16px",
          backgroundColor: "#ffffff",
          borderRadius: "16px",
          boxShadow: "0 4px 12px rgba(0,0,0,0.05)",
        },
      };

    case "nested-accordion":
      return {
        id,
        type: "nested-accordion",
        content: "Nested Accordion",
        accordionAllowMultiple: false,
        accordionActiveIds: [`acc_${Date.now()}_1`],
        accordionItems: [
          { id: `acc_${Date.now()}_1`, title: "1. What features are included in ForgeStudio?", icon: "help-circle" },
          { id: `acc_${Date.now()}_2`, title: "2. How does document persistence work?", icon: "database" },
          { id: `acc_${Date.now()}_3`, title: "3. Can I export clean React or HTML code?", icon: "code" },
        ],
        children: [],
        styles: {
          width: "100%",
          marginTop: "16px",
          marginBottom: "16px",
          paddingTop: "12px",
          paddingRight: "12px",
          paddingBottom: "12px",
          paddingLeft: "12px",
          backgroundColor: "#ffffff",
          borderRadius: "16px",
          boxShadow: "0 4px 12px rgba(0,0,0,0.05)",
        },
      };

    default:
      return {
        id,
        type,
        content: "Element",
        styles: {
          marginTop: "8px",
          marginBottom: "8px",
        },
      };
  }
}

// ==========================================
// Main WebsiteEditor Component
// ==========================================

